[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["chenej <chenej@gzyitop.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
failure = "0.1.1"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["tera_templates"]